export const PERMISSIONS = {
  CATEGORIES: {
    CREATE: 'CREATE_CATEGORY',
    READ: 'READ_CATEGORY',
    UPDATE: 'UPDATE_CATEGORY',
    DELETE: 'DELETE_CATEGORY',
  },
  EXPENSE: {
    CREATE: 'CREATE_EXPENSE',
    READ: 'READ_EXPENSE',
    UPDATE: 'UPDATE_EXPENSE',
    DELETE: 'DELETE_EXPENSE',
  }
};
